sudo: false

os: osx

language: go

go:
  - 1.5.1

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - GOMAXPROCS=8

cache:
  directories:
  - ~/Library/Caches/Homebrew

before_install:
  - go get -d -v -u github.com/zchee/docker-machine-xhyve

script:
  - make install
